Update npc_arena_1v1.cpp
/home/travis/build/NoffearrDeathProjecT/DeathCore/src/server/scripts/Custom/npc_arena_1v1.cpp:74:37: fatal error: 
      unused variable 'err' [-Wunused-variable]
        GroupJoinBattlegroundResult err = ERR_GROUP_JOIN_BATTLEGROUND_FAIL;