Update npc_arena_1v1.cpp
/home/travis/build/NoffearrDeathProjecT/DeathCore/src/server/scripts/Custom/npc_arena_1v1.cpp:43:16: fatal error: 
      unused variable 'guid' [-Wunused-variable]
        uint64 guid = player->GetGUID();