Update npc_arena_1v1.cpp
/home/travis/build/NoffearrDeathProjecT/DeathCore/src/server/scripts/Custom/npc_arena_1v1.cpp:38:51: fatal error: 
      unused parameter 'me' [-Wunused-parameter]
    bool JoinQueueArena(Player* player, Creature* me)